# Site settings
title: pajamaw
email: pjpeterww@gmail.com
url: https://pajamaw.github.io
description: "PJ Wickwire writes stuff here"
# skills: "" not sure if I like this areas anymore
meta_author: PJ Wickwire

collections: 
  projects:
    output: false

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
#contact: static

# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: pajamaw

color:
  primary:  d9d9d9 #80B3FF
  primary-rgb: "53,53,53"
  secondary:  353535 #3e5b7f
  secondary-dark: 99c1d8 #A2122F

footer:
  copyright: PJ Wickwire
  location: New York, NY
  social: Find Me Online

social:
  - title: envelope
    url: mailto:pjpeterww@gmail.com
  - title: linkedin
    url: http://linkedin.com/in/pjwickwire
  - title: instagram
    url: http://instagram.com/pajamaw
  - title: github
    url: http://github.com/pajamaw

address:
  - line: New York, NY

markdown: kramdown
permalink: pretty
