# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55517eeb79c103e38a94ed4a52124f7e9ff0ce47230e899cbb5935b1d7c96e57b481f763bd2f115e3867b60f72877f9db556e230e97bd981bac838303cbb27ed

test:
  secret_key_base: 291fe659b08b5961483470de76f7f3a7be7218a223ae65416d3803a448d610dfe4d8e980688b1b29fee6ae77a93f83fb463afcdac369bbeab1521af6cb8dfe7c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
